### ISSUE TITLE
How to modify this tool to support other languages?

### ISSUE THREAD

**Issue by BensenHsu** [editor-js/translate-inline#3]
Hi @talyguryn , can I customize this tool to translate other languages? I don't know how to build a custom inline tool. I checked the tutorial on https://editorjs.io/, but still have no idea how to create a real one in my Typescript project. I tried many methods, including uploading the /dist/bundle.js to my project, but the tool icon won't show up in the inline toolbar. Please enlighten me. Thanks.

**Comment by talyguryn** [comment]
at this moment this tool translates any input string to english. im going to add a new config param to define target language.

if you are interested in the development of this plugin, then in the readme there is a [development](https://github.com/editor-js/translate-inline#run-package-builder) section with the necessary commands.

if you are interested in the general workflow of creating such a plugin from scratch, then I will write a guide with examples in the form of an article or video

**Comment by BensenHsu** [comment]
> at this moment this tool translates any input string to english. im going to add a new config param to define target language.
> 
> if you are interested in the development of this plugin, then in the readme there is a [development](https://github.com/editor-js/translate-inline#run-package-builder) section with the necessary commands.
> 
> if you are interested in the general workflow of creating such a plugin from scratch, then I will write a guide with examples in the form of an article or video

@talyguryn Looking forward to your tutorial! I would like to try it myself after your video is live since I want to use DeepL as the engine.

**Comment by talyguryn** [comment]
@BensenHsu you can use docker image for translator backend which supports defining target language as GET param.

endpoint url in editor.js config:

`http://localhost:5000/translate?text=` — translate to english by default
`http://localhost:5000/translate?lang=de&text=` — translate to german

**Comment by BensenHsu** [comment]
> @BensenHsu you can use docker image for translator backend which supports defining target language as GET param.
> 
> endpoint url in editor.js config:
> 
> `http://localhost:5000/translate?text=` — translate to english by default `http://localhost:5000/translate?lang=de&text=` — translate to german

Thank you @talyguryn ! Is this backed with Google or DeepL?
